site_name: My Local TechDocs Site

theme:
  name: material
  palette:
    scheme: default
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Process:
      - Development:
          - Overview: process/development/index.md
          - Story Points: process/development/story_points.md
  - Forum: forum/index.md
  - Addins:
      - Available Addins: addins/index.md
      - Acumatica:
          - Overview: addins/acumatica/index.md
      - Solidworks:
          - Overview: addins/solidworks/index.md