site_name: CADTalk Documentation
repo_url: https://github.com/jmccann2000/tech-docs  # Link to your GitHub/GitLab repo

theme:
  name: material
  palette:
    scheme: default
    primary: 'indigo'
    accent: 'indigo'
  font:
    text: 'Roboto'
    code: 'Roboto Mono'
  features:
    - search.highlight
    - search.share

nav:
  - Home: index.md
  - Process:
      - Development:
          - Sprint Rituals:
              - process/development/sprint_rituals/sprint_schedule.md
              - process/development/sprint_rituals/sprint_planning.md
              - process/development/sprint_rituals/show_and_tell.md
              - process/development/sprint_rituals/sprint_retrospective.md
              - process/development/sprint_rituals/epic_refinement.md
              - process/development/sprint_rituals/backlog_refinement.md
          - Overview: process/development/index.md
          - Story Points: process/development/story_points.md
          - Log Maintenence: process/development/log_maintenance.md
  - Forum: forum/index.md
  - Addins:
      - Addins: addins/index.md
      - Acumatica:
          - Overview: addins/acumatica/index.md
      - Solidworks:
          - Overview: addins/solidworks/index.md



          