name: Trigger auto deployment for tech-docs

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/tech-docs-AutoDeployTrigger-fb3b6e57-30a8-4b02-bc88-1f33e6b8d882.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.TECHDOCS_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.TECHDOCS_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.TECHDOCS_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: jakescontainers.azurecr.io
          registryUsername: ${{ secrets.TECHDOCS_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.TECHDOCS_REGISTRY_PASSWORD }}
          containerAppName: tech-docs
          resourceGroup: personal_projects
          imageToBuild: jakescontainers.azurecr.io/tech-docs:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


